services:
  web:
    environment:
      - PDF_AUTH_MODE=none
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_BUCKET_NAME=test-bucket
      - AWS_REGION=eu-west-1
      - AWS_ENDPOINT_URL_S3=http://s3mock:9090
      - AWS_S3_FORCE_PATH_STYLE=true

  api:
    environment:
      - DANGEROUS_DISABLE_AUTH=true

  s3mock:
    image: adobe/s3mock:latest@sha256:4f064ff91fc1e72e723e7329288ea73580310ccff3f426b9f68fc93854be645c
    ports:
      - "9090:9090"
      - "9191:9191"
    environment:
      - initialBuckets=test-bucket
      - root=/data
    volumes:
      - s3data:/data

volumes:
  s3data:
