services:
  api:
    environment:
      - DANGEROUS_DISABLE_AUTH=true

  web:
    environment:
      - PDF_AUTH_MODE=none
      - AUTH_SECRET=foobar
      - NEXTAUTH_URL=http://localhost:3000/api/auth
      - GCP_BUCKET_NAME=test-bucket
      - GCS_MOCK_API_ENDPOINT=http://gcs_mock:9023
    depends_on:
      gcs_mock:
        condition: service_started

  gcs_mock:
    image: oittaa/gcp-storage-emulator:latest
    environment:
      - PORT=9023
    ports:
      - "9023:9023"
    volumes:
      - gcs_data:/storage
    command: ["start", "--default-bucket", "test-bucket"]

volumes:
  gcs_data:
