packages:
  - apps/*
  - packages/*
  - nuget-client/*

autoInstallPeers: false

injectWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - pdf-text-reader@5.1.1

onlyBuiltDependencies:
  - puppeteer

overrides:
  undici@>=7.0.0 <7.18.2: ">=7.18.2"

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - jose@4.15.9
  - semver@6.3.1
