apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{api.name}}"
  namespace: "{{team}}"
  labels:
    team: "{{team}}"
spec:
  env:
    - name: PORT
      value: "4000"
    - name: AZURE_TENANT_ID
      value: "{{azure_tenant_id}}"
    - name: AZURE_APPLICATION_ID
      value: "{{azure_app_id}}"
    - name: GIT_SHA
      value: "{{git_sha}}"
  ingresses:
    - "{{api.ingress}}"
  accessPolicy:
    inbound:
      rules:
        - application: "{{web.name}}"
          namespace: "{{team}}"
  port: 4000
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      memory: 1024Mi
  readiness:
    path: /health
    failureThreshold: 3
    initialDelay: 20
    periodSeconds: 5
    timeout: 1
  liveness:
    path: /health
    failureThreshold: 3
    initialDelay: 30
    periodSeconds: 10
    timeout: 1
