apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brevgen2-web
  namespace: plattform
spec:
  env:
    - name: PDF_API_URL
      value: http://brevgen2-api
    - name: PDF_API_KEY
      value: foobar
    - name: AWS_REGION
      value: eu-west-1
    - name: AWS_BUCKET_NAME
      value: "{{s3bucket}}"
  envFrom:
    - secret: nais-test-aws-sdk
    - secret: azure-devops-pat-code-read
  ingresses:
    - https://brevgen2.dev.atil.cloud.nais.io
    - https://brevgen2.intern.dev.arbeidstilsynet.no/
  accessPolicy:
    outbound:
      rules:
        - application: brevgen2-api
      external:
        - host: "{{s3bucket}}.s3.eu-west-1.amazonaws.com"
        # Azure DevOps REST API
        - host: dev.azure.com
        - host: spsprodweu1.vssps.visualstudio.com
        - host: spsprodweu2.vssps.visualstudio.com
        - host: spsprodweu3.vssps.visualstudio.com
  image: "{{image}}"
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
