apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{web.name}}"
  namespace: "{{team}}"
  labels:
    team: "{{team}}"
  annotations:
    # Increase buffer size to handle large cookies from NextAuth
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  env:
    - name: AZURE_APPLICATION_ID
      value: "{{azure_app_id}}"
    - name: NEXTAUTH_URL
      value: "{{web.ingress}}/api/auth"
    - name: PDF_API_URL
      value: "http://{{api.name}}"
    - name: PDF_AUTH_MODE
      value: bearer
    - name: AWS_REGION
      value: eu-west-1
    - name: AWS_BUCKET_NAME
      value: "{{s3bucket}}"
  envFrom:
    - secret: nais-test-aws-sdk # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
    - secret: azure-devops-pat-code-read # AZURE_DEVOPS_PAT
    - secret: brevgen2-azure-app-client-secret # AZURE_CLIENT_SECRET
    - secret: brevgen2-authjs-secret # AUTH_SECRET
  ingresses:
    - "{{web.ingress}}"
  accessPolicy:
    outbound:
      rules:
        - application: "{{api.name}}"
      external:
        - host: "{{s3bucket}}.s3.eu-west-1.amazonaws.com"
        # Azure DevOps REST API
        - host: dev.azure.com
        - host: spsprodweu1.vssps.visualstudio.com
        - host: spsprodweu2.vssps.visualstudio.com
        - host: spsprodweu3.vssps.visualstudio.com
  image: "{{image}}"
  port: 3000
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 192Mi
  readiness:
    path: /api/health
  liveness:
    path: /api/health
