repos:
  - repo: local
    hooks:
      - id: csharpier
        name: format with CSharpier
        entry: dotnet csharpier format .
        language: dotnet
        pass_filenames: false
        additional_dependencies:
          - csharpier:1.2.6
