parameters:
  - name: initialJobsDependsOn
    type: string
    default: ""

  - name: env
    type: string

  - name: tags
    type: string

  - name: awsCredentialsApi
    type: string

  - name: awsCredentialsWeb
    type: string

  - name: region
    type: string

  - name: infraBucket
    type: string

  - name: chromiumLayerBucket
    type: string

  - name: chromiumVersion
    type: string

  - name: imageName
    type: string

  - name: stackParametersApi
    type: string

  - name: stackParametersFargate
    type: string

  ### should not need changing
  - name: samCapabilities
    type: string
    default: "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"

# UploadLayer        DeployEcr
#    │                  │
#    │                  │
#    ▼                  ▼
# DeployApi         UploadWebImage
#    │                  │
#    └────────┬─────────┘
#             │
#             ▼
#        DeployFargate

jobs:
  - job: UploadLayer
    dependsOn: ${{ parameters.initialJobsDependsOn }}
    steps:
      - script: python -m pip install -r requirements.txt
        workingDirectory: "apps/api"
        displayName: "Install script dependencies"

      - task: AWSShellScript@1
        displayName: "Run upload script"
        inputs:
          workingDirectory: "apps/api"
          awsCredentials: ${{ parameters.awsCredentialsApi }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          failOnStandardError: true
          inlineScript: python upload-layer.py --bucket-name ${{ parameters.chromiumLayerBucket }} --chromium-version ${{ parameters.chromiumVersion }} --skip-confirmation

  - job: DeployApi
    dependsOn: UploadLayer
    steps:
      - template: pnpm/setup-pnpm.yaml@Templates

      - script: pnpm typecheck
        displayName: "Type check"
        workingDirectory: "apps/api"

      - script: pnpm lint
        displayName: "Lint"

      - script: pnpm circular
        displayName: "Circular dependencies check"

      - script: pnpm test
        displayName: "Test"
        workingDirectory: "apps/api"

      - script: pnpm build
        displayName: "Build code"
        workingDirectory: "apps/api"

      - script: sam build
        displayName: "Build infrastructure"
        workingDirectory: "apps/api"

      - task: AWSShellScript@1
        displayName: Deploy
        inputs:
          workingDirectory: "apps/api"
          awsCredentials: ${{ parameters.awsCredentialsApi }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          inlineScript: >-
            sam deploy --force-upload
            --no-fail-on-empty-changeset
            --capabilities ${{ parameters.samCapabilities }}
            --stack-name brevgenerator2-api-${{ parameters.env }}
            --s3-prefix brevgenerator2-api-${{ parameters.env }}
            --s3-bucket ${{ parameters.infraBucket }}
            --parameter-overrides ${{ parameters.stackParametersApi }} ChromiumVersion=${{ parameters.chromiumVersion }} ChromiumLayerBucket=${{ parameters.chromiumLayerBucket }}
            --tags ${{ parameters.tags }}

  - job: DeployEcr
    dependsOn: ${{ parameters.initialJobsDependsOn }}
    displayName: Deploy ECR
    steps:
      - script: sam build
        displayName: "Build infrastructure"
        workingDirectory: "apps/preview-web/ecr-infra"

      - task: AWSShellScript@1
        displayName: "Deploy infrastructure"
        inputs:
          workingDirectory: "apps/preview-web/ecr-infra"
          awsCredentials: ${{ parameters.awsCredentialsWeb }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          inlineScript: >-
            sam deploy --force-upload
            --no-fail-on-empty-changeset
            --capabilities ${{ parameters.samCapabilities }}
            --stack-name brevgenerator2-web-ecr-${{ parameters.env }}
            --s3-prefix brevgenerator2-web-ecr-${{ parameters.env }}
            --s3-bucket ${{ parameters.infraBucket }}
            --parameter-overrides ${{ parameters.stackParametersApi }} EcrRepositoryName=${{ parameters.imageName }}
            --tags ${{ parameters.tags }}

  - job: UploadWebImage
    dependsOn: DeployEcr
    steps:
      - script: "docker build . -t ${{ parameters.imageName }} -f apps/preview-web/Dockerfile"
        workingDirectory: "."
        displayName: "Build image"

      - task: AWSShellScript@1
        name: SetEcrUrl
        displayName: "Set variable ecrUrl"
        inputs:
          workingDirectory: "apps/preview-web/ecr-infra"
          awsCredentials: ${{ parameters.awsCredentialsWeb }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          failOnStandardError: true
          inlineScript: |
            awsAccount=$(aws sts get-caller-identity --query Account --output text)
            ecrUrl="$awsAccount.dkr.ecr.${{ parameters.region }}.amazonaws.com"
            echo "ecrUrl:$ecrUrl"
            echo "##vso[task.setvariable variable=ecrUrl;isoutput=true]$ecrUrl"

      - script: |
          sudo apt-get update
          sudo apt-get install -y amazon-ecr-credential-helper
        displayName: "Install Amazon ECR Credential Helper"

      - script: |
          ecrUrl=$(SetEcrUrl.ecrUrl)
          mkdir -p ~/.docker
          cat <<EOF > ~/.docker/config.json
          {
            "credHelpers": {
              "$ecrUrl": "ecr-login"
            }
          }
          EOF
        displayName: "Configure Docker for ECR Credential Helper"

      - task: AWSShellScript@1
        displayName: "Tag and upload image"
        inputs:
          workingDirectory: "apps/preview-web/ecr-infra"
          awsCredentials: ${{ parameters.awsCredentialsWeb }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          failOnStandardError: true
          inlineScript: |
            imageName=${{ parameters.imageName }}
            ecrUrl=$(SetEcrUrl.ecrUrl)
            region=${{ parameters.region }}
            echo "imageName:$imageName ecrUrl:$ecrUrl region:$region"
            docker tag "${imageName}:latest" "${ecrUrl}/${imageName}:latest"
            docker push "${ecrUrl}/${imageName}:latest"

  - job: DeployFargate
    dependsOn:
      - UploadWebImage # image must be in ECR when ECS tries to deploy
      - DeployApi # need to retrieve stack outputs for the api-stack
    variables:
      ecrUrl: $[ dependencies.UploadWebImage.outputs['SetEcrUrl.ecrUrl'] ]
    steps:
      - task: AWSShellScript@1
        displayName: "Set variable imageUri"
        inputs:
          awsCredentials: ${{ parameters.awsCredentialsWeb }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          failOnStandardError: true
          inlineScript: |
            awsAccount=$(aws sts get-caller-identity --query Account --output text)
            ecrUrl=$(ecrUrl)
            imageName=${{ parameters.imageName }}
            imageDigest=$(aws ecr describe-images --repository-name "$imageName" --image-ids imageTag=latest --query "imageDetails[0].imageDigest" --output text)
            imageUri="${ecrUrl}/${imageName}@${imageDigest}"
            echo "imageUri:$imageUri"
            echo "##vso[task.setvariable variable=imageUri]$imageUri"

      - task: AWSShellScript@1
        displayName: "Get API Key"
        inputs:
          awsCredentials: ${{ parameters.awsCredentialsApi }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          failOnStandardError: true
          inlineScript: |
            envName=${{ parameters.env }}
            stackName="brevgenerator2-api-${envName}"
            echo "stackName:$stackName"
            ssmParameterApiKeyId=$(aws cloudformation describe-stacks --stack-name "$stackName" --query "Stacks[0].Outputs[?OutputKey=='ParameterStoreApiKeyId'].OutputValue" --output text)
            echo "ssmParameterApiKeyId:$ssmParameterApiKeyId"
            apiKeyId=$(aws ssm get-parameter --name "$ssmParameterApiKeyId" --query "Parameter.Value" --output text)
            apiKey=$(aws apigateway get-api-key --api-key "$apiKeyId" --include-value --query "value" --output text)
            echo "##vso[task.setvariable variable=apiKey;issecret=true]$apiKey"

      - script: sam build
        displayName: "Build infrastructure"
        workingDirectory: "apps/preview-web/infra"

      - task: AWSShellScript@1
        displayName: "Deploy infrastructure"
        inputs:
          workingDirectory: "apps/preview-web/infra"
          awsCredentials: ${{ parameters.awsCredentialsWeb }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          arguments: "$(apiKey)"
          inlineScript: >-
            sam deploy --force-upload
            --no-fail-on-empty-changeset
            --capabilities ${{ parameters.samCapabilities }}
            --stack-name brevgenerator2-web-fargate-${{ parameters.env }}
            --s3-prefix brevgenerator2-web-fargate-${{ parameters.env }}
            --s3-bucket ${{ parameters.infraBucket }}
            --parameter-overrides ${{ parameters.stackParametersFargate }} ImageURI=$(imageUri) PdfApiKey=$1
            --tags ${{ parameters.tags }}
