parameters:
  - name: env
    type: string

  - name: tags
    type: string

  - name: awsCredentialsWeb
    type: string

  - name: region
    type: string

  - name: infraBucketWeb
    type: string

  - name: stackParametersFargate
    type: string

  ### should not need changing
  - name: samCapabilities
    type: string
    default: "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"

jobs:
  - job: DeployBucket
    steps:
      - script: sam build
        displayName: "Build infrastructure"
        workingDirectory: "apps/preview-web/infra"

      - task: AWSShellScript@1
        displayName: "Deploy infrastructure"
        inputs:
          workingDirectory: "apps/preview-web/infra"
          awsCredentials: ${{ parameters.awsCredentialsWeb }}
          regionName: ${{ parameters.region }}
          scriptType: "inline"
          disableAutoCwd: true
          arguments: "$(apiKey)"
          inlineScript: >-
            sam deploy --force-upload
            --no-fail-on-empty-changeset
            --capabilities ${{ parameters.samCapabilities }}
            --stack-name brevgenerator2-web-fargate-${{ parameters.env }}
            --s3-prefix brevgenerator2-web-fargate-${{ parameters.env }}
            --s3-bucket ${{ parameters.infraBucketWeb }}
            --parameter-overrides ${{ parameters.stackParametersFargate }}
            --tags ${{ parameters.tags }}
