pool:
  vmImage: "ubuntu-latest"

trigger:
  batch: true
  branches:
    include:
      - develop

variables:
  - group: brevgenerator2

steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      sshKeySecureFile: github_deploy_key_brevgen2

  - script: |
      git config --global user.name "Azure DevOps pipeline"
      git config --global user.email "grunde.thorheim@arbeidstilsynet.no"
      git remote add github git@github.com:Arbeidstilsynet/brevgen2.git
      git push github HEAD:main
    displayName: "Mirror to GitHub"
