pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: Templates
      type: git
      name: felles-pipeline-templates
      ref: develop

trigger:
  batch: true
  branches:
    include:
      - develop
  paths:
    exclude:
      - src # legacy
      - "**/*.md" # markdown
      - "**/*.mdat" # dynamisk markdown
      - ".*"

stages:
  - stage: Brevgen2DeployVerifikasjon
    displayName: Verifi
    jobs:
      - template: templates/brevgen2-deploy.yml
        parameters:
          env: dev
          awsCredentialsWeb: DevPubDeploy
          region: eu-west-1
          infraBucketWeb: "infra-dev-deploy-pub-bucket"
          stackParametersFargate: >-
            Env=dev
          tags: >-
            Environment=dev
            RepoName=$(Build.Repository.Name)
            Version=$(Build.SourceBranchName)-$(Build.SourceVersion)
            CostCenter=3103
            ApplicationName=brevgenerator2
