resources:
  repositories:
    - repository: Templates
      type: git
      name: felles-pipeline-templates
      ref: develop

trigger:
  batch: true
  branches:
    include:
      - develop
  paths:
    exclude:
      - src # legacy
      - "**/*.md" # markdown
      - "**/*.mdat" # dynamisk markdown

jobs:
  - job: Build
    steps:
      - template: pnpm/setup-pnpm.yaml@Templates

      - script: pnpm lint
        displayName: "Lint"

      - script: pnpm typecheck
        displayName: "Type check"

      - script: pnpm check
        displayName: "Formatting check"

      - script: pnpm circular
        displayName: "Circular dependencies check"

      # filtrer ut nuget-client så denne pipeline ikke trenger håndtere dotnet
      - script: pnpm test --filter=!nuget-client
        displayName: "Test"

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: "**/junit.xml"
        condition: succeededOrFailed()

      - task: PublishCodeCoverageResults@2
        inputs:
          summaryFileLocation: "**/coverage/clover.xml"
        condition: succeededOrFailed()

      - script: pnpm build --filter=!nuget-client
        displayName: "Build"
