pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: Templates
      type: git
      name: felles-pipeline-templates
      ref: develop

trigger:
  batch: true
  tags:
    include:
      - "brevgenerator2-v*"

variables:
  - group: brevgenerator2

stages:
  - stage: Brevgen2DeployValid
    displayName: Valid
    jobs:
      - template: templates/brevgen2-deploy.yml
        parameters:
          env: test
          awsCredentials: TestDeploy
          region: eu-west-1
          infraBucket: "infra-test-deploy-bucket"
          chromiumLayerBucket: test-brevgenerator2-lambda-layers
          chromiumVersion: "131.0.1"
          imageName: test-brevgenerator2-web
          stackParametersApi: >-
            Env=test
            DomainName=brevgenerator2-api-valid.arbeidstilsynet.no
            CrossAccountRoute53RoleArn=arn:aws:iam::250640723606:role/felles-cfn-extensions-prod-crossaccount-r53-role
            DomainHostedZoneId=Z073533223SF44MXB039V
          stackParametersFargate: >-
            Env=test
            DomainName=brevgenerator-valid.arbeidstilsynet.no
            CrossAccountRoute53RoleArn=arn:aws:iam::250640723606:role/felles-cfn-extensions-prod-crossaccount-r53-role
            DomainHostedZoneId=Z073533223SF44MXB039V
            PdfApiUrl=https://brevgenerator2-api-valid.arbeidstilsynet.no
            AzureDevopsPat=$(AZURE_DEVOPS_PAT)
          tags: >-
            Environment=test
            RepoName=$(Build.Repository.Name)
            Version=$(Build.SourceBranchName)-$(Build.SourceVersion)
            CostCenter=3103
            ApplicationName=brevgenerator2

  - stage: Brevgen2IntegrationTests
    displayName: Integration Tests
    jobs:
      - job: Testcontainer
        steps:
          - template: pnpm/setup-pnpm.yaml@Templates
          - script: "pnpm test:integration"
            displayName: "Test"
            workingDirectory: "apps/api"

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: "**/junit.xml"
              mergeTestResults: true
              failTaskOnMissingResultsFile: true
            condition: succeededOrFailed()

          - task: PublishPipelineArtifact@1
            displayName: "Publish snapshots"
            inputs:
              targetPath: "apps/api/integration-tests/__snapshots__"
              artifact: "integration-tests-snapshots-$(System.StageName)-$(System.JobAttempt)"
              publishLocation: pipeline
            condition: failed()

  - stage: Brevgen2DeployProd
    displayName: Prod
    jobs:
      - job: Confirmation
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: ""
              instructions: "Fortsett når validering er ferdig"

      - template: templates/brevgen2-deploy.yml
        parameters:
          initialJobsDependsOn: Confirmation
          env: prod
          awsCredentials: ProdDeployCD
          region: eu-west-1
          infraBucket: "infra-prod-deploy-bucket"
          chromiumLayerBucket: prod-brevgenerator2-lambda-layers
          chromiumVersion: "131.0.1"
          imageName: prod-brevgenerator2-web
          stackParametersApi: >-
            Env=prod
            DomainName=brevgenerator2-api.arbeidstilsynet.no
            CrossAccountRoute53RoleArn=arn:aws:iam::250640723606:role/felles-cfn-extensions-prod-crossaccount-r53-role
            DomainHostedZoneId=Z073533223SF44MXB039V
          stackParametersFargate: >-
            Env=prod
            DomainName=brevgenerator.arbeidstilsynet.no
            CrossAccountRoute53RoleArn=arn:aws:iam::250640723606:role/felles-cfn-extensions-prod-crossaccount-r53-role
            DomainHostedZoneId=Z073533223SF44MXB039V
            PdfApiUrl=https://brevgenerator2-api.arbeidstilsynet.no
            AzureDevopsPat=$(AZURE_DEVOPS_PAT)
          tags: >-
            Environment=prod
            RepoName=$(Build.Repository.Name)
            Version=$(Build.SourceBranchName)-$(Build.SourceVersion)
            CostCenter=3103
            ApplicationName=brevgenerator2
