resources:
  repositories:
    - repository: Templates
      type: git
      name: felles-pipeline-templates
      ref: develop

trigger:
  branches:
    include:
      - develop

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - deployment: FellesBrevgeneratorApiDeployVerifikasjon
    displayName: felles-brevgenerator-api-deploy-verifikasjon
    environment: aws-verifikasjon
    condition: eq(variables['Build.SourceBranchName'], 'develop')
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: dotnet/deploy-dotnetcore-capabilities-template-dotnet6.yml@Templates
              parameters:
                awsBucket: infra-dev-deploy-bucket
                stackName: felles-brevgenerator-dev-all-cf
                awsCredentials: DevDeploy
                region: eu-west-1
                restoreSolution: "src/Brevgenerator.sln"
                workingDir: "src/"
                nugetConfigPath: "src/nuget.config"
                capabilities: >-
                  CAPABILITY_IAM
                  CAPABILITY_AUTO_EXPAND
                stackParameters: >-
                  env=dev
                tags: >-
                  Environment=dev
                  RepoName=$(Build.Repository.Name)
                  Version=$(Build.SourceBranchName)-$(Build.SourceVersion)
                  ProjectName=digisam
                  Name=felles-brevgenerator
                  Application=felles-brevgenerator
                  Owner=magnus.alvestad.mikalsen@arbeidstilsynet.no
                  CostCenter=2016
