resources:
  repositories:
    - repository: Templates
      type: git
      name: felles-pipeline-templates
      ref: develop

trigger:
  tags:
    include:
      - "v*"

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: FellesBrevgeneratorApiDeployValidering
    displayName: felles-brevgenerator-api-deploy-validering
    jobs:
      - deployment: FellesBrevgeneratorApiDeployValidering
        displayName: felles-brevgenerator-api-deploy-validering
        environment: aws-validering
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: dotnet/deploy-dotnetcore-capabilities-template-dotnet8.yml@Templates
                  parameters:
                    awsBucket: infra-test-deploy-bucket
                    stackName: felles-brevgenerator-test-all-cf
                    awsCredentials: TestDeploy
                    region: eu-west-1
                    restoreSolution: "src/Brevgenerator.sln"
                    workingDir: "src/"
                    nugetConfigPath: "src/nuget.config"
                    capabilities: >-
                      CAPABILITY_IAM
                      CAPABILITY_AUTO_EXPAND
                    stackParameters: >-
                      env=test
                    tags: >-
                      Environment=test
                      RepoName=$(Build.Repository.Name)
                      Version=$(Build.SourceBranchName)
                      ProjectName=digisam
                      Name=felles-brevgenerator
                      Application=felles-brevgenerator
                      Owner=magnus.alvestad.mikalsen@arbeidstilsynet.no
                      CostCenter=2016

  - stage: FellesBrevgeneratorApiDeployProduksjon
    displayName: felles-brevgenerator-api-deploy-produksjon
    jobs:
      - deployment: FellesBrevgeneratorApiDeployProduksjon
        displayName: felles-brevgenerator-api-deploy-produksjon
        environment: aws-produksjon
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: dotnet/deploy-dotnetcore-capabilities-template-dotnet8.yml@Templates
                  parameters:
                    awsBucket: infra-prod-deploy-bucket
                    stackName: felles-brevgenerator-prod-all-cf
                    awsCredentials: ProdDeploy
                    region: eu-west-1
                    restoreSolution: "src/Brevgenerator.sln"
                    workingDir: "src/"
                    nugetConfigPath: "src/nuget.config"
                    capabilities: >-
                      CAPABILITY_IAM
                      CAPABILITY_AUTO_EXPAND
                    stackParameters: >-
                      env=prod
                    tags: >-
                      Environment=prod
                      RepoName=$(Build.Repository.Name)
                      Version=$(Build.SourceBranchName)
                      ProjectName=digisam
                      Name=felles-brevgenerator
                      Application=felles-brevgenerator
                      Owner=magnus.alvestad.mikalsen@arbeidstilsynet.no
                      CostCenter=2016
