resources:
  repositories:
    - repository: Templates
      type: git
      name: felles-pipeline-templates
      ref: develop

trigger:
  batch: true
  branches:
    include:
      - develop
  paths:
    include:
      - src

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - deployment: FellesBrevgeneratorApiDeploySandbox
    displayName: felles-brevgenerator-api-deploy-sandbox
    environment: aws-sandbox
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: dotnet/deploy-dotnetcore-capabilities-template-dotnet6.yml@Templates
              parameters:
                awsBucket: infra-sandbox-deploy-bucket
                stackName: felles-brevgenerator-sandbox-all-cf
                awsCredentials: SandboxDeploy
                region: eu-west-1
                restoreSolution: "src/Brevgenerator.sln"
                workingDir: "src/"
                nugetConfigPath: "src/nuget.config"
                capabilities: >-
                  CAPABILITY_IAM
                  CAPABILITY_AUTO_EXPAND
                stackParameters: >-
                  env=sandbox
                tags: >-
                  Environment=sandbox
                  RepoName=$(Build.Repository.Name)
                  Version=$(Build.SourceBranchName)-$(Build.SourceVersion)
                  ProjectName=digisam
                  Name=felles-brevgenerator
                  Application=felles-brevgenerator
                  Owner=magnus.alvestad.mikalsen@arbeidstilsynet.no
                  CostCenter=2016
