AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack for Brevgenerator2 workspace bucket

Parameters:
  Env:
    Type: String
    Description: Environment name, e.g. dev/prod/myname

Resources:
  # **************************************
  # S3 Bucket
  # **************************************
  WorkspaceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Env}-at-brevgenerator2-workspace"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # **************************************
  # Outputs
  # **************************************
Outputs:
  S3WorkspaceBucket:
    Value: !Ref WorkspaceBucket
