name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      nais: ${{ steps.nais.outputs.changes_detected }}
      brevgen2: ${{ steps.brevgen2.outputs.changes_detected }}
      nuget-client: ${{ steps.nuget-client.outputs.changes_detected}}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Nais config changed?
        uses: Arbeidstilsynet/action-check-changes@6e51077b178b819e4194f40e32bd562df0954f3f # v1
        id: nais
        with:
          # correctly handle both push and pr events to get the right base ref
          base-ref: ${{ github.event_name == 'pull_request' && 'origin/main' ||
            github.event.before }}
          include: |
            .github/workflows/ci.yaml
            .nais

      - name: Brevgen2 changed?
        uses: Arbeidstilsynet/action-check-changes@6e51077b178b819e4194f40e32bd562df0954f3f # v1
        id: brevgen2
        with:
          base-ref: ${{ github.event_name == 'pull_request' && 'origin/main' ||
            github.event.before }}
          include: |
            .github/workflows/ci.yaml
            apps/
            packages/
            package.json
            pnpm*.yaml
            .ox*rc.json
          exclude: |
            **/*.md
            **/.gitignore
            packages/nuget-client/

      - name: Nuget-client changed?
        uses: Arbeidstilsynet/action-check-changes@6e51077b178b819e4194f40e32bd562df0954f3f # v1
        id: nuget-client
        with:
          base-ref: ${{ github.event_name == 'pull_request' && 'origin/main' ||
            github.event.before }}
          include: |
            .github/workflows/ci.yaml
            nuget-client/

  validate-nais:
    needs: changes
    if: needs.changes.outputs.nais == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: .nais
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install nais-cli
        run: |
          NAIS_GPG_KEY="/etc/apt/keyrings/nav_nais_gar.asc"
          curl -sfSL "https://europe-north1-apt.pkg.dev/doc/repo-signing-key.gpg" | sudo dd of="$NAIS_GPG_KEY"
          echo "deb [arch=amd64 signed-by=$NAIS_GPG_KEY] https://europe-north1-apt.pkg.dev/projects/nais-io nais-ppa main" | sudo tee /etc/apt/sources.list.d/nav_nais_gar.list
          sudo apt update
          sudo apt install nais
      - run: nais --version
      - run: nais validate --vars-file vars-dev.yaml api.yaml web.yaml
      - run: nais validate --vars-file vars-prod.yaml api.yaml web.yaml

  build:
    needs: changes
    if: needs.changes.outputs.brevgen2 == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: Arbeidstilsynet/action-pnpm-setup@618fbc6ee30a13d077086cafba92b4e6cdca0f78 # v1

      - run: pnpm typecheck
        name: "Type check"

      - run: pnpm circular
        name: "Circular dependencies check"

      - run: pnpm test --filter=!nuget-client
        name: "Test"
        id: test

      # known issue: status check will be attached to the wrong workflow
      # https://github.com/orgs/community/discussions/24616
      # https://github.com/EnricoMi/publish-unit-test-result-action/issues/12
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        if: ${{ !cancelled() && (steps.test.outcome == 'success' || steps.test.outcome == 'failure') }}
        with:
          files: "**/junit.xml"
          check_name: "Brevgen2 Unit Test Results"

      - run: pnpm build --filter=!nuget-client
        name: "Build"

  prek:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      # workaround to install oxlint-tsgolint without overriding additional_dependencies in .pre-commit-config.yaml
      - uses: Arbeidstilsynet/action-pnpm-setup@618fbc6ee30a13d077086cafba92b4e6cdca0f78 # v1
      - uses: j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16 # v2

  testcontainer:
    needs: changes
    if: needs.changes.outputs.brevgen2 == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: Arbeidstilsynet/action-pnpm-setup@618fbc6ee30a13d077086cafba92b4e6cdca0f78 # v1

      - run: "pnpm test:integration"
        id: test
        working-directory: "apps/api"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        if: ${{ !cancelled() && (steps.test.outcome == 'success' || steps.test.outcome == 'failure') }}
        with:
          files: "**/junit.xml"
          check_name: "Integration Test Results"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ !cancelled() && steps.test.outcome == 'failure' }}
        with:
          name: integration-test-snapshots
          path: apps/api/integration-tests/__snapshots__/

  nuget-client:
    needs: changes
    if: needs.changes.outputs.nuget-client == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Build and Test .NET solution
        uses: Arbeidstilsynet/action-dotnet-build@7112207464cac6fa7273a6806d76dc5ad03fe87e # v4
        with:
          working-directory: "."
          skip-csharpier: true
          skip-style-analyzers: true
