name: Build and deploy
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: nais/docker-build-push@791ebb6f74b82849c742a9bc9c97abe44c6c111f # v0
        id: docker-build-push-api
        with:
          team: plattform
          image_suffix: api
          # web app must be built from root for pnpm lockfile and packages to be available
          docker_context: "."
          dockerfile: "./apps/api/Dockerfile"
          build_args: |
            CHROMIUM_VERSION: "134.*"
      - uses: nais/deploy/actions/deploy@70ac914d5785b492f1247df72e04b8420c1a6cb7 # v2
        env:
          CLUSTER: dev
          RESOURCE: .nais/api.yaml
          VAR: image=${{ steps.docker-build-push-api.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-push-api.outputs.telemetry }}

  deploy_web:
    name: Deploy web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: nais/docker-build-push@791ebb6f74b82849c742a9bc9c97abe44c6c111f # v0
        id: docker-build-push-web
        with:
          team: plattform
          image_suffix: web
          # web app must be built from root for pnpm lockfile and packages to be available
          docker_context: "."
          dockerfile: "./apps/preview-web/Dockerfile"
      - uses: nais/deploy/actions/deploy@70ac914d5785b492f1247df72e04b8420c1a6cb7 # v2
        env:
          CLUSTER: dev
          RESOURCE: .nais/web.yaml
          VAR: image=${{ steps.docker-build-push-web.outputs.image }},s3bucket=dev-at-brevgenerator2-workspace-bucket
          TELEMETRY: ${{ steps.docker-build-push-web.outputs.telemetry }}
